version: '3.7'

networks:
  ingress:
    external: true

services:
  ingress:
    image: traefik:v1.7.18-alpine
    restart: unless-stopped
	labels:
	  - traefik.enable=true
	  - traefik.frontend.rule=Host:ingress.kaii.dev
	volumes:
	  - /var/run/docker.sock:/var/run/docker.sock:ro
	  - ./traefik.toml:/traefik.toml
	  - ./acme.json:/acme.json
	ports:
	  - 8080:8080
	  - 80:80
	  - 443:443