debug = false

logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]

[log]
[accessLog]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$MzjY4yJp$mvBaZJw0SuIY9z8SnA3cp."]
[entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[retry]

[api]
entrypoint="dashboard"

[acme]
email = "srodriguez@kaii.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
endpoint = "unix://var/run/docker.sock"
domain = "kaii.com"
watch = true
exposedByDefault = false
network = "ingress"
